// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed Icons/main_icon.png
var resourceMainiconPngData []byte
var resourceMainiconPng = &fyne.StaticResource{
	StaticName:    "Icons/main_icon.png",
	StaticContent: resourceMainiconPngData,
}
