// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed Icons/main_icon.png
var ResourceMainiconPngData []byte

var ResourceMainiconPng = &fyne.StaticResource{
	StaticName:    "Icons/main_icon.png",
	StaticContent: ResourceMainiconPngData,
}
