name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Windows Binary
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build GUI application
      run: go build -ldflags="-H=windowsgui -s -w" -o share-my-clipboard.exe
      
    - name: Build debug version (with console)
      run: go build -ldflags="-s -w" -o share-my-clipboard-debug.exe

    - name: Run tests
      run: go test -v ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-binaries
        path: |
          share-my-clipboard.exe
          share-my-clipboard-debug.exe

  release:
    name: Create Release
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-binaries
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          share-my-clipboard.exe
          share-my-clipboard-debug.exe
        body: |
          ## Share My Clipboard ${{ github.ref_name }}
          
          ### 📦 Downloads
          - **share-my-clipboard.exe** — Production build (GUI only, no console)
          - **share-my-clipboard-debug.exe** — Debug build (with console for troubleshooting)
          
          ### 🚀 Quick Start
          1. Download `share-my-clipboard.exe`
          2. Run the executable
          3. Connect to other devices and start sharing!
          
          See [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for full documentation.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint Code
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
