name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Windows Binary
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build GUI application
      run: go build -ldflags="-H=windowsgui -s -w" -o share-my-clipboard.exe

    - name: Build debug version (with console)
      run: go build -ldflags="-s -w" -o share-my-clipboard-debug.exe

    - name: Run tests
      run: go test -v ./...

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: |
          share-my-clipboard.exe
          share-my-clipboard-debug.exe

  lint:
    name: Lint Code
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        args: --timeout=5m --out-format=colored-line-number
      continue-on-error: true
